### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by lolmaus** [growcss/sass-config-manager#46]
You've got CI set up, why don't you add unit tests?

Some links for you in random order:

http://thejameskyle.com/bootcamp/
https://github.com/wealthfront/sassaby
https://github.com/HugoGiraudel/SassyTester
https://github.com/ericam/true
https://github.com/penman/SassUnit

There are also nice articles over the web.

**Comment by prisis** [comment]
I have unit test ;), check travis, im using true

**Comment by lolmaus** [comment]
Ah, awesome! Then they need to be updated before releasing the local/global feature.

And they should fail for your take on it (before my PR).
