### ISSUE TITLE
Release as an eyeglass addon

### ISSUE THREAD

**Issue by lolmaus** [growcss/sass-config-manager#47]
[Eyeglass](https://github.com/sass-eyeglass/eyeglass) is a package manager for Sass, built on top of npm.

Details on how to support Eyeglass is here: https://github.com/sass-eyeglass/eyeglass/blob/master/docs/eyeglass_modules/index.md#bringing-eyeglass-to-existing-projects

I personally don't use it yet, but this is definitely the way to go. Your addon is pure awesomeness and it should be available via the most modern distribution channel!

**Comment by prisis** [comment]
Hey, i fixed all erros, i hope :D and added support for eyeglass.

Can you take a look?

**Comment by lolmaus** [comment]
I'm not using Eyeglass yet (its support in my framework is limited to `scss` while I'm mostly using `sass`), so I can't check.

But there's something fishy. I think that `sassDir` in [eyeglass-exports.js](https://github.com/sass-projects/sass-config-manager/blob/ab2b708a9635897ea374a0d70556b68dc7cabf21/eyeglass-exports.js#L7) should be consistent with `main` in [package.json](https://github.com/sass-projects/sass-config-manager/blob/ab2b708a9635897ea374a0d70556b68dc7cabf21/package.json#L10).

You should decide whether the `sass/` dir should be consumable by apps.

Most Sass libraries don't have a dedicated build step (i. e. no `dist/`). They simply offer a main file (e. g. `sass/_sass-config-manager.scss`) that imports all partials in correct order. And the user has a choice of whether to import the main file or a specific partial.

So from my point of view you should either point both endpoints at `dist/` or get rid of the build step and use `sass/`.
